### PR TITLE
From xul to jpm

### LINKED ISSUE #23: Does not work on Firefox 43
Per https://addons.mozilla.org/en-US/firefox/addon/wallabag/reviews/769266/.

### PR DESCRIPTION
**Pull request by Aldarone**
Rewrite of the addon using JPM : 

* Firefox 43 compatibility
* Restartless installation

Fixes #23 :wink:

### CODE REVIEW

**Comment by nicosomb** [comment]
> Restartless installation 

:clap:

**Comment by nicosomb** [comment]
@tcitworld who can review this PR?

**Comment by tcitworld** [comment]
Me. Doing it right now.

**Comment by tcitworld** [comment]
:+1: We need @jogaulupeau to publish it.

**Comment by nicosomb** [comment]
maybe @jogaulupeau can transfer to us the access

**Comment by jogaulupeau** [comment]
I don't know if I can transfer the access without loose my account.
Could you please send me the .xpi while we search a more efficient way to do this ?

**Comment by tcitworld** [comment]
Here you are : [@wallabag-2.0.0.xpi.zip](https://github.com/wallabag/firefox-ext/files/108230/wallabag-2.0.0.xpi.zip) (zipped to let Github upload it)

**Comment by jogaulupeau** [comment]
Votre module n'a pas passé la validation et a généré 1 erreur.

    L'identifiant ne correspond à aucun module.

**Comment by tcitworld** [comment]
OK. Will fix.

**Comment by jogaulupeau** [comment]
OK, V2.0.0 waiting for review.

**Comment by jogaulupeau** [comment]
It's online.

**Comment by tcitworld** [comment]
:+1:

**Comment by tcitworld** [comment]
Also, is there a way you could update the screenshot with this one ?

wallabag-firefox-ext

**Comment by jogaulupeau** [comment]
Done

**Pull request merged**
