### PR TITLE
Functionality to have a tab instead f a dialog. Handy for users of tiled WM.

### PR DESCRIPTION
**Pull request by stepardo**
I saw that the extension was rewritten in the meantime, and my changes won't apply. I am posting the pull request to get feedback, on if you are interested in the functionality, so that I can decide whether or not I will port if to jpm as well.

### CODE REVIEW

**Comment by tcitworld** [comment]
Indeed, I personally use the [Social API](http://doc.wallabag.org/en/User/save_your_first_article.html#firefox-social-api-service) in i3 so I never thought about this issue. It's indeed very useful (though it should be disabled by default thanks to the options).

I would be interested to merge your work if you would be kind enough to port it to jpm. **However**, the extension ~~will~~ should be rewritten (or at least much changed) soon to make use of the OAuth API available in wallabag v2, so please consider this. ;-)

**Comment by stepardo** [comment]
The social API is broken in the following scenario: Have a server with one public DNS, and run two webapps with social service. In only one social service can exist for one domain because they are using the very domain as the identifier for the service.

Anyhow, I think I will spend the effort to port my change to jpm.

**Comment by tcitworld** [comment]
> The social API is broken in the following scenario: Have a server with one public DNS, and run two webapps with social service. In only one social service can exist for one domain because they are using the very domain as the identifier for the service.

That's one particular use. ;-)

**Comment by stepardo** [comment]
Implemented this in the new API, which I also like *much* better.

**Pull request closed without merging**
